name: Periodic Update

on:
  workflow_dispatch:
  schedule:
    - cron: "19 13 * * *"

jobs:
  fetch:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Download New File
      run: |
        mkdir temp-download/
        if curl --output temp-download/playlists_v2.txt https://r2-pc.s3.amazonaws.com/playlists_v2.txt; then
          echo "File download successful."
        else
          echo "File download failed."
          exit 1
        fi

    - name: Check for Differences
      id: check-differences
      run: |
        if ! diff --brief temp-download/playlists_v2.txt data/playlists_v2.txt; then
          echo "Files are different."
          echo "FILE_UPDATED=true" >> $GITHUB_ENV
        else
          echo "Files are the same. Skipping commit."
          echo "FILE_UPDATED=false" >> $GITHUB_ENV
        fi

    - name: Overwrite File
      if: steps.check-differences.outcome == 'success' && env.FILE_UPDATED == 'true'
      run: |
        mv temp-download/playlists_v2.txt data/playlists_v2.txt

    - name: Commit and Push Changes
      if: steps.check-differences.outcome == 'success' && env.FILE_UPDATED == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add data/playlists_v2.txt
        git commit --message="Update file"
        git push
